spring:
  kafka:
    consumer:
      group-id: grp-hallo
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

tpd:
  topic-name: hallo-topic
  messages-per-request: 10